/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author garcia_d
 */
public class LoginInfo extends javax.swing.JPanel {

    /**
     * Creates new form LoginInfo
     */
    public LoginInfo() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jButtonLight = new javax.swing.JButton();
        jButtonDark = new javax.swing.JButton();

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/TIQ Logo Login D.png"))); // NOI18N

        jButtonLight.setBackground(new java.awt.Color(73, 181, 172));
        jButtonLight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/light.png"))); // NOI18N
        jButtonLight.setBorder(null);
        jButtonLight.setContentAreaFilled(false);
        jButtonLight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLight.setDoubleBuffered(true);
        jButtonLight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLightActionPerformed(evt);
            }
        });

        jButtonDark.setBackground(new java.awt.Color(73, 181, 172));
        jButtonDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/dark.png"))); // NOI18N
        jButtonDark.setBorder(null);
        jButtonDark.setContentAreaFilled(false);
        jButtonDark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDark.setFocusPainted(false);
        jButtonDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButtonLight)
                .addGap(50, 50, 50)
                .addComponent(jButtonDark)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLight, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDark, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLightActionPerformed
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/TIQ Logo Login L.png")));
    }//GEN-LAST:event_jButtonLightActionPerformed

    private void jButtonDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDarkActionPerformed
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/TIQ Logo Login D.png")));
    }//GEN-LAST:event_jButtonDarkActionPerformed

    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#49B5AC"), 0, getHeight(), Color.decode("#49B5AC"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDark;
    private javax.swing.JButton jButtonLight;
    private javax.swing.JLabel jLabelLogo;
    // End of variables declaration//GEN-END:variables
}
