/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.component;

import com.raven.model.Model_Prioritat;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author aigardo
 */
public class Prioritat extends javax.swing.JPanel {

    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }

    private Color color1;
    private Color color2;
    
    public Prioritat() {
        initComponents();
        setOpaque(false);
        color1 = Color.BLACK;
        color2 = Color.WHITE;
    }
    
    public void setData (Model_Prioritat data) {
        jLabelTitle.setText(data.getTitle());
        jLabelP1.setText(data.getPriotitat1());
        jLabelP1V.setText(data.getPriotitat1valor());
        jLabelP2.setText(data.getPriotitat2());
        jLabelP2V.setText(data.getPriotitat2valor());
        jLabelP3.setText(data.getPriotitat3());
        jLabelP3V.setText(data.getPriotitat3valor());
        jLabelP4.setText(data.getPriotitat4());
        jLabelP4V.setText(data.getPriotitat4valor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelP1 = new javax.swing.JLabel();
        jLabelP1V = new javax.swing.JLabel();
        jLabelP2 = new javax.swing.JLabel();
        jLabelP2V = new javax.swing.JLabel();
        jLabelP3 = new javax.swing.JLabel();
        jLabelP3V = new javax.swing.JLabel();
        jLabelP4 = new javax.swing.JLabel();
        jLabelP4V = new javax.swing.JLabel();

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(245, 245, 245));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Title");

        jLabelP1.setBackground(new java.awt.Color(204, 255, 204));
        jLabelP1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelP1.setForeground(new java.awt.Color(245, 245, 245));
        jLabelP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP1.setText("Prioritat 1");

        jLabelP1V.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelP1V.setForeground(new java.awt.Color(245, 245, 245));
        jLabelP1V.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP1V.setText("Values");

        jLabelP2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelP2.setForeground(new java.awt.Color(245, 245, 245));
        jLabelP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP2.setText("Prioritat 2");

        jLabelP2V.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelP2V.setForeground(new java.awt.Color(245, 245, 245));
        jLabelP2V.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP2V.setText("Values");

        jLabelP3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelP3.setForeground(new java.awt.Color(245, 245, 245));
        jLabelP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP3.setText("Prioritat 3");

        jLabelP3V.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelP3V.setForeground(new java.awt.Color(245, 245, 245));
        jLabelP3V.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP3V.setText("Values");

        jLabelP4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelP4.setForeground(new java.awt.Color(245, 245, 245));
        jLabelP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP4.setText("Prioritat 4");

        jLabelP4V.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelP4V.setForeground(new java.awt.Color(245, 245, 245));
        jLabelP4V.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelP4V.setText("Values");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelP4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelP1V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP2V, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabelP3V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelP4V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelP1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabelP1V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelP2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabelP2V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelP3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabelP3V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelP4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabelP4V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.setColor(new Color(255, 255, 255, 50));
        g2.fillOval(getWidth() - (getHeight() / 2), 10, getHeight(), getHeight());
        g2.fillOval(getWidth() - (getHeight() / 2) - 20, getHeight() / 2 + 20, getHeight(), getHeight());
        super.paintComponent(grphcs);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelP1;
    private javax.swing.JLabel jLabelP1V;
    private javax.swing.JLabel jLabelP2;
    private javax.swing.JLabel jLabelP2V;
    private javax.swing.JLabel jLabelP3;
    private javax.swing.JLabel jLabelP3V;
    private javax.swing.JLabel jLabelP4;
    private javax.swing.JLabel jLabelP4V;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
