/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.formadd;

import com.raven.utils.DeptCrud;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author aigardo
 */
public class Form_Add_Department_1 extends javax.swing.JPanel {

    /**
     * Creates new form Form_Add_Department
     */
    
    public Form_Add_Department_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabelDept = new javax.swing.JLabel();
        jTextFieldDept = new javax.swing.JTextField();
        jLabelPhone = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabelDesc = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(55, 55, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 181, 172));
        jLabel1.setText("Afegir Departament");

        jButtonBack.setBackground(new java.awt.Color(55, 55, 55));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/back.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelDept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDept.setForeground(new java.awt.Color(73, 181, 172));
        jLabelDept.setText("Departament");

        jTextFieldDept.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldDept.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldDept.setBorder(null);

        jLabelPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPhone.setForeground(new java.awt.Color(73, 181, 172));
        jLabelPhone.setText("Teléfon");

        jTextFieldPhone.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldPhone.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldPhone.setBorder(null);

        jLabelDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDesc.setForeground(new java.awt.Color(73, 181, 172));
        jLabelDesc.setText("Descripció");

        jTextFieldDesc.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldDesc.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldDesc.setBorder(null);

        jButtonClear.setBackground(new java.awt.Color(55, 55, 55));
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/clean.png"))); // NOI18N
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(55, 55, 55));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/adddept.png"))); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(55, 55, 55));
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/edit.png"))); // NOI18N
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack)
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabelDept)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldDept, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPhone)
                        .addGap(30, 30, 30)))
                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDesc)
                            .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBack)
                    .addComponent(jLabel1))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDept)
                    .addComponent(jTextFieldDept, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPhone)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabelDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonEdit))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Add_Frame add_Frame = (Add_Frame) SwingUtilities.getWindowAncestor(this);
        add_Frame.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        cleanFormAdd();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        
        String dept = jTextFieldDept.getText().toString();
        String phone = jTextFieldPhone.getText().toString();
        String desc = jTextFieldDesc.getText().toString();
        
        //Creo instancia de la clase DeptCrud
        DeptCrud dc = new DeptCrud();
        
        dc.setDept(dept);
        dc.setPhone(phone);
        dc.setDesc(desc);
        
        if (dc.addDept()) {
            JOptionPane.showMessageDialog(this, "S'ha donat d'alta el departament " + dept);
        }
        
        cleanFormAdd();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        String dept_edit = jTextFieldDept.getText().toString();
        String phone_edit = jTextFieldPhone.getText().toString();
        String desc_edit = jTextFieldDesc.getText().toString();
        
        //Creo instancia de la clase DeptCrud
        DeptCrud dc = new DeptCrud();
        
        dc.setDept(dept_edit);
        dc.setPhone(phone_edit);
        dc.setDesc(desc_edit);
        
        if (dc.modifyDept()) {
            JOptionPane.showMessageDialog(this, "S'ha actualitzat el departament " + dept_edit);
        }
        
        Add_Frame form_Add = (Add_Frame) SwingUtilities.getWindowAncestor(this);
        form_Add.dispose();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void cleanFormAdd() {
        jTextFieldDept.setText(null);
        jTextFieldPhone.setText(null);
        jTextFieldDesc.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClear;
    public static javax.swing.JButton jButtonEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDept;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelPhone;
    public static javax.swing.JTextField jTextFieldDept;
    public static javax.swing.JTextField jTextFieldDesc;
    public static javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
